---
- name: Pull file from S3 bucket
  hosts: localhost
  connection: local

  tasks:
    - name: Download file from S3
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: sanjay.txt
        dest: /opt/s3files/sanjay.txt
        mode: get
      vars:
        s3_bucket: "rapolu-bucket-3879"

